---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s %(name)-20s%(levelname)-8s%(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
root:
    level: DEBUG
    handlers: [console]
