
run:
	xhost +
	docker-compose run --rm proply
build:
	docker-compose build # --no-cache

# proply --bem --naca --n 40 --resolution 40 --dir build/ --param /props/flywoo_robo_rb1202.5_11500kv.json --auto
